# Generated by Django 6.0.3 on 2026-03-16 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_userpresence_messagereaction_typingindicator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="sentiment",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="toxicity_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="typingindicator",
            name="timestamp",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="userpresence",
            name="is_online",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="typingindicator",
            index=models.Index(
                fields=["timestamp"], name="chat_typing_timesta_9ec105_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpresence",
            index=models.Index(
                fields=["is_online", "status"], name="chat_userpr_is_onli_98ad32_idx"
            ),
        ),
    ]
